### ISSUE TITLE
please share your source of data

### ISSUE THREAD

**Issue by tommyngx** [pietz/knee-mri-segmentation#2]
Dear @pietz !
Could you please share the source of data? I would like to contact you for your support! 
Please contact me via my email: tommyfederation@gmail.com
Many thanks!
Stay strong and Healthy!
Regards,
Tommy

**Comment by pietz** [comment]
Not possible. It's a closed dataset from a study with no license to share the images.

**Comment by tommyngx** [comment]
Thank you for your reply!
